
name: AutoGreen

on:
  push:
    branches:
      - master
  schedule:
    - cron: "*/6 * * * *"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Auto green
        run: |
          git config --local user.email "xmanvcom@gmail.com"
          git config --local user.name "xmanv"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          echo '#' >> a.html
          git add .
          git commit --allow-empty -m "one commit one day keeps your girlfriend away"
          git push
